spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:565452}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: payment-event:com.example.orderservice.dto.PaymentEvent

server:
  port: ${SERVER_PORT:8081}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}